# This is a basic workflow to help you get started with Actions

name: deploy telegram-bot-gateway

# Controls when the workflow will run
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#       - name: Create secret
#         uses: "finnp/create-file-action@master"
#         env:
#           FILE_NAME: "telegram-bot-gateway/src/main/resources/${{ secrets.TELEGRAM_BOT_SECRET_NAME }}"
#           FILE_DATA: "${{ secrets.TELEGRAM_BOT_SECRET_VALUE }}"
          
#       - name: Create file
#         run: |
#           echo ${{ secrets.TELEGRAM_BOT_SECRET_VALUE }} >> telegram-bot-gateway/src/main/resources/${{ secrets.TELEGRAM_BOT_SECRET_NAME }}
#           cat telegram-bot-gateway/src/main/resources/${{ secrets.TELEGRAM_BOT_SECRET_NAME }}

      - uses: 1arp/create-a-file-action@0.2
        with:
          path: 'telegram-bot-gateway/src/main/resources/'
          file: '${{ secrets.TELEGRAM_BOT_SECRET_NAME }}'
          content: |
            ${{ secrets.TELEGRAM_BOT_SECRET_VALUE }}
          
      - name: Run a one-line script
        run: |
          cat telegram-bot-gateway/src/main/resources/${{ secrets.TELEGRAM_BOT_SECRET_NAME }}
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B clean package -DskipTests
        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
#       - name: Run a one-line script
#         run: |
#           echo "files"
#           cd telegram-bot-gateway
#           ls
#           echo "files"
#           cd target
#           ls
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: telegram-bot-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/telegram-bot-gateway:latest

      # Runs a set of commands using the runners shell
      - name: deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker stop telegram-bot-gateway || true
            docker pull mxpnk/telegram-bot-gateway
            docker run -d --network my_network mxpnk/telegram-bot-gateway
            docker logout
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          user: root
          key: ${{ secrets.DEPLOY_SERVER_KEY}}
