spring:
  jpa:
    hibernate: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: ${pg.schema}
  datasource:
    url: jdbc:postgresql://${pg.host}:5432/${pg.schema}
    username: ${pg.user}
    password: ${pg.pass}